WITH CTE_DRUG_INFO_LU AS (
	SELECT c2.CONCEPT_ID AS INGREDIENT_CONCEPT_ID, c2.CONCEPT_NAME AS INGREDIENT_CONCEPT_NAME, 
		c1.CONCEPT_ID AS DRUG_CONCEPT_ID, c1.CONCEPT_NAME AS DRUG_CONCEPT_NAME, 
		ds.AMOUNT_VALUE, ds.AMOUNT_UNIT_CONCEPT_ID, c3.CONCEPT_NAME AS AMOUNT_UNIT_CONCEPT_NAME,
		ds.NUMERATOR_VALUE, ds.NUMERATOR_UNIT_CONCEPT_ID, c4.CONCEPT_NAME AS NUMERATOR_UNIT_CONCEPT_NAME,
		CASE WHEN ds.AMOUNT_VALUE IS NULL THEN ds.NUMERATOR_VALUE ELSE ds.AMOUNT_VALUE END AS VALUE,
		CASE WHEN ds.AMOUNT_VALUE IS NULL THEN c4.CONCEPT_NAME ELSE c3.CONCEPT_NAME END AS VALUE_UNIT
	FROM @cdmDatabaseSchema.CONCEPT c1
		LEFT OUTER JOIN @cdmDatabaseSchema.DRUG_STRENGTH ds
			ON ds.DRUG_CONCEPT_ID = c1.CONCEPT_ID
		LEFT OUTER JOIN @cdmDatabaseSchema.CONCEPT c2
			ON c2.CONCEPT_ID = ds.INGREDIENT_CONCEPT_ID
		LEFT OUTER JOIN @cdmDatabaseSchema.CONCEPT c3 
			ON c3.CONCEPT_ID = ds.AMOUNT_UNIT_CONCEPT_ID
		LEFT OUTER JOIN @cdmDatabaseSchema.CONCEPT c4 
			ON c4.CONCEPT_ID = ds.NUMERATOR_UNIT_CONCEPT_ID
	WHERE c1.CONCEPT_ID IN (
		SELECT DESCENDANT_CONCEPT_ID FROM @cdmDatabaseSchema.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID = @INGREDIENT_CONCEPT_ID
	)
), 
CTE_DAILY_DOSE AS (
	SELECT c.COHORT_DEFINITION_ID, c.SUBJECT_ID, c.COHORT_START_DATE, c.COHORT_END_DATE, 
		l.INGREDIENT_CONCEPT_ID, l.INGREDIENT_CONCEPT_NAME, 
		l.DRUG_CONCEPT_ID, l.DRUG_CONCEPT_NAME, 
		l.VALUE, l.VALUE_UNIT, 
		CASE WHEN QUANTITY IS NULL OR QUANTITY = 0 THEN 1 ELSE QUANTITY END AS QUANTITY, 
		CASE WHEN DAYS_SUPPLY IS NULL THEN 1 ELSE DAYS_SUPPLY END AS DAYS_SUPPLY, 
		(CASE WHEN QUANTITY IS NULL OR QUANTITY = 0 THEN 1 ELSE QUANTITY END/CASE WHEN DAYS_SUPPLY IS NULL THEN 1 ELSE DAYS_SUPPLY END) * VALUE AS DAILY_DOSE
	FROM @cohortDatabaseSchema.@cohortTable c
		JOIN @cdmDatabaseSchema.DRUG_EXPOSURE de
			ON de.PERSON_ID = c.SUBJECT_ID
			AND de.DRUG_EXPOSURE_START_DATE = c.COHORT_START_DATE
			{@psMatched == 1}?{AND de.PERSON_ID IN ( SELECT subjectid FROM @cohortDatabaseSchema.@cohortTable_StratPop WHERE TREATMENT = @treatmentGroup)}
		JOIN CTE_DRUG_INFO_LU l
			ON l.DRUG_CONCEPT_ID = de.DRUG_CONCEPT_ID
			AND l.INGREDIENT_CONCEPT_ID = @INGREDIENT_CONCEPT_ID
		JOIN @cdmDatabaseSchema.CONCEPT c1
			ON c1.CONCEPT_ID = de.DRUG_CONCEPT_ID
			AND c1.CONCEPT_ID IN (
				SELECT DESCENDANT_CONCEPT_ID FROM @cdmDatabaseSchema.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID = 	@INGREDIENT_CONCEPT_ID
			)
	WHERE COHORT_DEFINITION_ID = @COHORT_DEFINITION_ID
	AND l.VALUE IS NOT NULL --74/1122612 were blank in codeine
	AND QUANTITY < 1000
	AND DAYS_SUPPLY < 365
)
SELECT '@COHORT_DEFINITION_ID' AS COHORT_DEFINITION_ID, 
  '@cohortTable' AS COHORT_TABLE,
  SUBJECT_ID, (SUM(DAILY_DOSE) * @MME) AS DAILY_DOSE_MME, COUNT(*) AS ROW_COUNT
FROM CTE_DAILY_DOSE dd
GROUP BY SUBJECT_ID
ORDER BY 2 